schema_version: 1

context:
  name: blissdata
  version: "2.4.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/blissdata-${{ version }}.tar.gz
  sha256: 8b40ec715183d14617da442b93cfa79843f30f812eda92ad5097b97955f66aa5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - memory_tracker = blissdata.redis_engine.memory_tracker:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - beartype
    - fabio >=0.12
    - h5py >=2.9
    - msgpack-python
    - numpy >=1.20
    - numpydantic <1.6.10
    - pydantic >=2.9
    - redis-py >=4.6.0
    - redis-om >=1.0,<2
    - silx >=1.1.0

tests:
  - python:
      imports:
        - blissdata
        - blissdata.redis_engine.scan
        - blissdata.redis_engine.store
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*
  - script:
      - memory_tracker --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Bliss data streaming client
  license: LGPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.esrf.fr/bliss/blissdata
  repository: https://gitlab.esrf.fr/bliss/blissdata
  documentation: https://bliss.gitlab-pages.esrf.fr/blissdata/

extra:
  recipe-maintainers:
    - proto3
    - beenje
